services:
  endee-enterprise:
    image: endee-enterprise:latest
    container_name: endee-enterprise
    ports:
      - "8080:8080"
    ulimits:
      nofile: 100000
# ----------------------------------------------------
# Logging Configuration Block
    logging:
      driver: "json-file" # Explicitly use the default driver
      options:
        # Set the max size of a single log file to 200 megabytes
        # Docker rotates the log file when it hits this limit
        max-size: "200m"
        # Set the maximum number of log files to keep
        # (200m * 5 files = 1000m or 1 GB total log space)
        max-file: "5"
# ----------------------------------------------------
    environment:
      NDD_NUM_THREADS: 0
      NDD_AUTH_TOKEN: "your_secure_token" # Required: set your auth token
    volumes:
      - nd-data:/data
    restart: unless-stopped

volumes:
  # Modify the 'device' path below to change the host directory used for data persistence
  nd-data:
    driver: local
    driver_opts:
      type: ext4
      o: bind
      device: /home/debian/mnt
